apiVersion: v2
name: scalardl
description: Implementation scalardl.
type: application
version: 1.2.2
appVersion: 2.1.0
deprecated: false
icon: https://scalar-labs.com/wp-content/themes/scalar/assets/img/logo_scalar.svg
keywords:
- envoy
- proxy
- ledger
- dlt
home: https://scalar-labs.com/
source: ["https://scalardl.readthedocs.io/en/latest/"]
maintainers:
  - name: Paul Dozancuk
    email: paul.dozancuk@scalar-labs.com
  - name: Yusuke Morimoto
    email: yusuke.morimoto@scalar-labs.com
