{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) ( .Values.envoy.prometheusRule.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: prometheus-operator
    release: prometheus
  name: {{ include "scalardl.fullname" . }}-envoy-prometheus-alerts-rules
{{- if .Values.envoy.prometheusRule.namespace }}
  namespace: {{ .Values.envoy.prometheusRule.namespace }}
{{- end }}
spec:
  groups:
  - name: EnvoyAlerts
    rules:
    - alert: EnvoyClusterDown
      expr: kube_deployment_spec_replicas{deployment="{{ include "scalardl.fullname" . }}-envoy"} - kube_deployment_status_replicas_unavailable{deployment="{{ include "scalardl.fullname" . }}-envoy"} == 0
      for: 1m
      labels:
        severity: critical
        app: Envoy
      annotations:
        summary: 'Envoy cluster is down'
        description: 'Envoy cluster is down, no resquest can be process.'

    - alert: EnvoyClusterDegraded
      expr: kube_deployment_status_replicas_unavailable{namespace="{{ .Release.Namespace }}", deployment="{{ include "scalardl.fullname" . }}-envoy"} >= 1
      for: 1m
      labels:
        severity: warning
        app: Envoy
      annotations:
        summary: 'Envoy cluster is running in a degraded mode'
        description: 'Envoy cluster is running in a degraded mode, some of the Envoy pods are not healthy.'

    - alert: EnvoyPodsPending
      expr: kube_pod_status_phase{namespace="{{ .Release.Namespace }}", pod=~"^{{ include "scalardl.fullname" . }}-envoy-.*", phase="Pending"} > 0
      for: 1m
      labels:
        severity: warning
        app: Envoy
      annotations:
        description: 'Pod {{`{{$labels.pod}}`}} in namespace {{`{{$labels.namespace}}`}} has been in pending status for more than 1 minute.'
        summary: 'Pod {{`{{$labels.pod}}`}} in namespace {{`{{$labels.namespace}}`}} in pending status'
    
    - alert: EnvoyPodsError
      expr: kube_pod_container_status_waiting_reason{namespace="{{ .Release.Namespace }}",reason!="ContainerCreating",pod=~"^{{ include "scalardl.fullname" . }}-envoy-.*"} > 0
      for: 1m
      labels:
        severity: warning
        app: Envoy
      annotations:
        description: 'Pod {{`{{$labels.pod}}`}} in namespace {{`{{$labels.namespace}}`}} has an error for more than 1 minute.'
        summary: 'Pod {{`{{$labels.pod}}`}} in namespace {{`{{$labels.namespace}}`}} has an error status'
{{- end }}
