apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scalardl.fullname" . }}-ledger
  labels:
    {{- include "scalardl-ledger.labels" . | nindent 4 }}
spec:
  minReadySeconds: 0
  replicas: {{ .Values.ledger.replicaCount }}
  selector:
    matchLabels:
      {{- include "scalardl-ledger.selectorLabels" . | nindent 6 }}
  {{- with .Values.ledger.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "scalardl-ledger.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
    {{- with .Values.ledger.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.ledger.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-ledger
          securityContext:
            {{- toYaml .Values.ledger.securityContext | nindent 12 }}
          image: "{{ .Values.ledger.image.repository }}:{{ .Values.ledger.image.version }}"
          imagePullPolicy: {{ .Values.ledger.image.pullPolicy }}
          ports:
          - containerPort: 50051
          - containerPort: 50052
          - containerPort: 50053
          env:
          - name: SCALAR_DB_CONTACT_POINTS
            value: "{{ .Values.ledger.scalarLedgerConfiguration.dbContactPoints }}"
          - name: SCALAR_DB_CONTACT_PORT
            value: "{{ .Values.ledger.scalarLedgerConfiguration.dbContactPort }}"
          - name: SCALAR_DB_USERNAME
            valueFrom:
              secretKeyRef:
              {{- if .Values.ledger.existingSecret }}
                name: {{ .Values.ledger.existingSecret }}
              {{- else }}
                name: {{ include "scalardl.fullname" . }}-ledger
              {{- end }}
                key: db-username
          - name: SCALAR_DB_PASSWORD
            valueFrom:
              secretKeyRef:
              {{- if .Values.ledger.existingSecret }}
                name: {{ .Values.ledger.existingSecret }}
              {{- else }}
                name: {{ include "scalardl.fullname" . }}-ledger
              {{- end }}
                key: db-password
          - name: SCALAR_DB_STORAGE
            value: "{{ .Values.ledger.scalarLedgerConfiguration.dbStorage }}"
          - name: SCALAR_DL_LEDGER_LOG_LEVEL
            value: "{{ .Values.ledger.scalarLedgerConfiguration.ledgerLogLevel }}"
          livenessProbe:
            exec:
              command:
              - /bin/grpc_health_probe
              - -addr=:50051
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.ledger.resources | nindent 12 }}
      {{- with .Values.ledger.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.ledger.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.ledger.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
