# Default values for scalar-envoy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# replicaCount -- number of replicas to deploy
replicaCount: 3

envoyConfiguration:
  # envoyConfiguration.adminAccessLogPath -- admin log path
  adminAccessLogPath: /dev/stdout
  # envoyConfiguration.scalardlAddress -- scalardl endpoint
  scalardlAddress: scalar-ledger-headless.default.svc.cluster.local

image:
  # image.repository -- Docker image
  repository: scalarlabs/scalar-envoy
  # image.pullPolicy -- Specify a imagePullPolicy
  pullPolicy: IfNotPresent

# imagePullSecrets -- Optionally specify an array of imagePullSecrets. Secrets must be manually created in the namespace.
imagePullSecrets: []

# nameOverride -- String to partially override scalar-envoy.fullname template (will maintain the release name)
nameOverride: ""

# fullnameOverride -- String to fully override scalar-envoy.fullname template
fullnameOverride: ""

strategy:
  rollingUpdate:
    # strategy.rollingUpdate -- The number of pods that can be created above the desired amount of pods during an update
    maxSurge: 0
    # strategy.rollingUpdate -- The number of pods that can be unavailable during the update process
    maxUnavailable: 1
  # strategy.type -- New pods are added gradually, and old pods are terminated gradually, e.g: Recreate or RollingUpdate
  type: RollingUpdate

# podSecurityContext -- PodSecurityContext holds pod-level security attributes and common container settings
podSecurityContext: {}
  # fsGroup: 2000

# securityContext -- Setting security context at the pod applies those settings to all containers in the pod
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
service:
  # service.type -- service types in kubernetes
  type: LoadBalancer
  # service.annotations -- Service annotations, e.g: prometheus, etc.
  annotations: {}
  ports:
    envoy:
      # service.ports.envoy.port -- envoy public port
      port: 50051
      # service.ports.envoy.targetPort -- envoy k8s internal name
      targetPort: 50051
      # service.ports.envoy.protocol -- envoy protocol
      protocol: TCP
    envoy-priv:
      # service.ports.envoy-priv.port -- nvoy public port
      port: 50052
      # service.ports.envoy-priv.targetPort -- envoy k8s internal name
      targetPort: 50052
      # service.ports.envoy-priv.protocol -- envoy protocol
      protocol: TCP

serviceMonitor:
  # serviceMonitor.enabled -- enable metrics collect with prometheus
  enabled: true
  # serviceMonitor.interval -- custom interval to retrieve the metrics
  interval: "15s"
  # serviceMonitor.namespace -- which namespace prometheus is located. by default monitoring
  namespace: monitoring

prometheusRule:
  # prometheusRule.enabled -- enable rules for prometheus
  enabled: false
  # prometheusRule.namespace -- which namespace prometheus is located. by default monitoring
  namespace: monitoring

# resources -- resources allowed to the pod
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# nodeSelector -- nodeSelector is form of node selection constraint
nodeSelector: {}

# tolerations -- Tolerations are applied to pods, and allow (but do not require) the pods to schedule onto nodes with matching taints.
tolerations: []

# affinity -- the affinity/anti-affinity feature, greatly expands the types of constraints you can express
affinity: {}
