apiVersion: v1
kind: Service
metadata:
  name: {{ include "scalar-dl.fullname" . }}-envoy
  labels:
    {{- include "scalar-dl-envoy.labels" . | nindent 4 }}
  annotations:
{{ toYaml .Values.envoy.service.annotations | indent 4 }}
spec:
  type: {{ .Values.envoy.service.type }}
  ports:
  {{- range $key, $value := .Values.envoy.service.ports }}
    - name: {{ $key }}
{{ toYaml $value | indent 6 }}
  {{- end }}
  selector:
    {{- include "scalar-dl-envoy.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scalar-dl.fullname" . }}-envoy-metrics
  labels:
    {{- include "scalar-dl-envoy.labels" . | nindent 4 }}
spec:
  ports:
  - name: admin
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    {{- include "scalar-dl-envoy.selectorLabels" . | nindent 4 }}
  type: ClusterIP
